/// <reference types="cypress"/>

// const { first } = require("cypress/types/lodash");

it('Login', () => {
    //Login page - credentials entering 
    cy.visit('https://dev.cash.paypro.pw:13000/')
    cy.get('[placeholder="Enter username"]').type('superadmin');
    cy.get('[placeholder="Enter password"]').type('superadmin');
    cy.get('[class="MuiButton-label"]').click();
    cy.get('[aria-controls="customized-menu"]').should('contain', "superadmin");
    console.log('superadmin successfully logged in, header displayed');
    cy.get('[d="M3 18h18v-2H3v2zm0-5h18v-2H3v2zm0-7v2h18V6H3z"]').click();
    cy.get('[href="/nodes"]').click(); 
    // cy.pause();
    //Merchant creating
    let merchantRandom = Math.random()*1000;
    merchantRandom = Math.trunc(merchantRandom);
    let merchantTitlePos = `cypressMerch${merchantRandom}`;
    const callback_link = 'https://google.com/';
    cy.get('.jss231 > .jss233 > .MuiButtonBase-root > .MuiButton-label').click();
    // cy.get('[class="MuiButtonBase-root MuiButton-root MuiButton-text"]').click();
    cy.get('[placeholder="Enter title"]').type(merchantTitlePos);
    cy.get('[placeholder="Enter callback link"]').type(callback_link);
    cy.get('[type="submit"]').click();
    cy.contains('Merchant created!').should('exist');


    //Resource tile elements

    //Room creating
    let roomRandom = Math.random()*1000;
    roomRandom = Math.trunc(roomRandom);
    let roomTitlePos = `cypressRoom${roomRandom}`
    cy.contains(merchantTitlePos).click();
    //Change CSS onto 'id="merchant4"' first 3 merchants generated by autotests
    cy.contains('[class="MuiPaper-root MuiAccordion-root jss239 Mui-expanded MuiAccordion-rounded MuiPaper-elevation1 MuiPaper-rounded"]', merchantTitlePos).find('[aria-label="Add"]').click()
    // cy.get('[class="MuiFormControl-root MuiTextField-root"]').type(roomTitlePos)
    cy.get('[name="club_name"]').type(merchantTitlePos);
    
    // cy.get('[placeholder="Enter title"]').type(merchantTitlePos);
    cy.get('[placeholder="Select timezone"] [title="Open"]').click();
    cy.contains('Kiev').click()
    // cy.get('[type="submit"]').click();

});